### ISSUE TITLE
Don't serialize properties without a setter

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulibYaml#13]
In general, this does not make much sense since they just silently fail when deserializing. For example, consider the following class:

```java
class Person {
   String firstName;
   String lastName;

   String getFirstName() { ... }
   void setFirstName(String value) { ... }
   String getLastName() { ... }
   void setLastName(String value) { ... }

   String getFullName() { return getFirstName() + getLastName() } // <-- no setter, "computed" property
}
```

This creates the yaml:

```yaml
- p1: Person
  firstName: Bob
  lastName: Bobson
  fullName: Bob Bobson # don' want that!
```
